development:
  database: postgres
  username: postgres
  password: 1144
  host: localhost

release:
  database: postgres
  username: postgres
  password: 1144
  host: 172.16.230.150

test:
  database: postgres
  username: postgres
  password: 1144
  host: localhost