development:
  database: postgres
  username: postgres
  password: 1144
  host: localhost

release:
  database: nil
  username: nil
  password: nil
  host: localhost

test:
  database: postgres
  username: postgres
  password: 1144
  host: localhost