development:
  database: postgres
  username: postgres
  password: 1144
  host: localhost

release:
  database: postgres
  username: postgres
  password: 1144
  host: 172.16.30.216

test:
  database: postgres
  username: postgres
  password: 1144
  host: localhost